### ISSUE TITLE
Bans - The block for the dapp store and icon for the side menu

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#12]
<img width="567" alt="Снимок экрана 2022-06-10 в 14 32 06" src="https://user-images.githubusercontent.com/94360080/173056003-0a035d3e-4fa7-4a55-911d-df36acd188a0.png">

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=2%3A332

<img width="243" alt="Снимок экрана 2022-06-10 в 14 34 18" src="https://user-images.githubusercontent.com/94360080/173056315-6b82766b-07c2-47ce-92b4-075183de00c3.png">

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=2%3A657

**Comment by viktarmikhan** [comment]
declined by @beam-mw
