### ISSUE TITLE
BANS - the Loader

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#13]
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=2%3A653

<img width="919" alt="Снимок экрана 2022-06-10 в 14 38 27" src="https://user-images.githubusercontent.com/94360080/173057021-810a2afb-5289-47e6-9775-39b62b2c4486.png">

**Comment by AndreyDyakonov** [comment]
Checked
