### ISSUE TITLE
BANS - FAQ

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#16]
Text will be later. 
every question will have the title and the text body

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=9%3A198
<img width="825" alt="Снимок экрана 2022-06-10 в 15 19 45" src="https://user-images.githubusercontent.com/94360080/173062879-ec3a53f8-40d4-45bd-aec5-ae647417daf1.png">

**Comment by VikMaevskaya** [comment]
After the last changes I've merged tasks #15 and #16

**Comment by VikMaevskaya** [comment]
When all texts will be ready we will merge the design
<img width="853" alt="Снимок экрана 2022-07-04 в 10 29 58" src="https://user-images.githubusercontent.com/94360080/177104185-c26964bb-0caf-43e2-9fbf-f26227070eeb.png">

**Comment by Denis-Asipenko** [comment]
1. fix the letter Q in the icon
<img width="120" alt="2022-07-08_14-25-17" src="https://user-images.githubusercontent.com/45556620/177983973-c4a2d5b4-a9a2-476d-8112-b8d04dd0ba30.png">
2.correct the numbering. after the question number 1, there are two questions number 3
<img width="1431" alt="2022-07-08_14-27-04" src="https://user-images.githubusercontent.com/45556620/177984217-8db72dd6-c7a0-472b-bee8-1f5f3bfc4f31.png">
