### ISSUE TITLE
BANS - My page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#18]
If the user doesn't have any favorites or owned domains, he will see the empty page with notification.
If user has any of them or both - separate task #21 #22 

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=40%3A1070
<img width="606" alt="Снимок экрана 2022-06-10 в 15 26 18" src="https://user-images.githubusercontent.com/94360080/173063852-7345e143-b411-4df5-bc64-24341c10eee2.png">

**Comment by AndreyDyakonov** [comment]
Please add "star" in  center of BANS icon (as in design)

![2022-07-11_14-31-54](https://user-images.githubusercontent.com/85252690/178255332-3b63375f-fb75-48ff-bd99-9b8be0e2bb30.png)
