### ISSUE TITLE
The search result (3 different pages)

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#2]
3 different pages with the search result

1. bans name is free (green)
2. wrong bans name (red)
3. bans name is unavailable (have been bought by the other user) (grey)

 please, use the beam's colours 

<img width="937" alt="Снимок экрана 2022-06-01 в 17 19 03" src="https://user-images.githubusercontent.com/94360080/171426709-22373803-00c0-4089-864e-19b67a6893a6.png">

**Comment by dariatarakanova** [comment]
1) Available https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=7%3A58
<img width="557" alt="image" src="https://user-images.githubusercontent.com/47353570/171662251-80dc5258-5a74-4774-874f-d2c96dd064cd.png">

2) Not available (bought by another) https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=7%3A261
<img width="594" alt="image" src="https://user-images.githubusercontent.com/47353570/171662309-ceb6a768-022e-4abc-969a-a6cc168df9c4.png">

3) Incorrect name https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=7%3A404
<img width="590" alt="image" src="https://user-images.githubusercontent.com/47353570/171662596-b8d3be08-c7dd-4dfa-80ca-fc32f4a9b4b5.png">
