### ISSUE TITLE
BANS - buying available domain

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#20]
when user click on available domain, the Register form is opened

<img width="526" alt="Снимок экрана 2022-06-13 в 14 48 12" src="https://user-images.githubusercontent.com/94360080/173347110-07a2cf11-0496-4ce6-88a1-8520c694ac09.png">

Registration Period - no limits. if the limit is needed - set 50 years. 
- prices: 
5+ character.BEAM names: $10 in BEAM per year.
4 character.BEAM names: $120 in BEAM per year.
3 character.BEAM names $320 in BEAM per year.

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=10%3A362
<img width="827" alt="Снимок экрана 2022-06-14 в 11 19 19" src="https://user-images.githubusercontent.com/94360080/173529304-6a910db8-fda8-47f9-be79-1b276474bae2.png">

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=40%3A586
<img width="392" alt="Снимок экрана 2022-06-13 в 15 21 10" src="https://user-images.githubusercontent.com/94360080/173352322-0dacddcc-3c51-41d7-8a38-bfde0b78c0a4.png">

After Transaction confirmation opens user's My page
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=40%3A798
<img width="911" alt="Снимок экрана 2022-06-13 в 15 32 01" src="https://user-images.githubusercontent.com/94360080/173354227-f4b76e31-991b-404b-a651-5b2dce52ea67.png">

**Comment by Denis-Asipenko** [comment]
there are no fix for item 1
item 3:
a)when the number of years for which user register a domain changes, the registration period does not change from below and remains until 2023
b) the price per year is 16 beam regardless of the number of letters in the name domain
there are no fix for item 4

**Comment by Denis-Asipenko** [comment]
checked
