### ISSUE TITLE
BANS - my page, all domains

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#21]
The list of the domains which the user owns.
the domain card:
- domain name
- expires date (grey period changed to red text if the term expires in less than 30 days)
- copy the domain name icon
- three dots menu ( renew subscription ( task #23  ), sell the domain (task #26 ))
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=104%3A718
<img width="706" alt="Снимок экрана 2022-06-13 в 22 10 24" src="https://user-images.githubusercontent.com/94360080/173427122-a4c5bd54-c9f5-4ba2-9a5b-5a91ab063854.png">

**Comment by AndreyDyakonov** [comment]
Remove from sale
1. Make the font as in the design
2. Change "close" to "cancel"
3. Make "remove" button red with black text and a black icon

![2022-07-21_11-27-43](https://user-images.githubusercontent.com/85252690/180170656-f35c5e2b-2f24-45a7-bff5-f17bb6f7597d.png)

4. Make the "prohibition" icon the same size as the cross

![2022-07-21_11-30-02](https://user-images.githubusercontent.com/85252690/180171117-b0dee444-1743-451d-80c9-418f670b0cca.png)

Change price 
1. Add Beam icon
2. Change "close" to "cancel" 
3. Change "Transfer" to "change"

![2022-07-21_11-31-34](https://user-images.githubusercontent.com/85252690/180171718-9fad5a97-49f8-4aed-977c-87188fa50a78.png)

4. If we have a domain with the maximum number of characters , then text goes outside the window
( need to either reduce the font size or make another alignment )

![image](https://user-images.githubusercontent.com/85252690/180172356-5351d46b-aa14-43e5-a26a-78158ef0b584.png)

**Comment by AndreyDyakonov** [comment]
1. Make domain name is bold
2. Make a "check of the ban" in black, as in the design

<img width="1367" alt="Снимок экрана 2022-07-25 в 13 55 41" src="https://user-images.githubusercontent.com/85252690/180763119-158cbd9e-77ca-47ce-87db-4e3bd466ee09.png">

**Comment by AndreyDyakonov** [comment]
Checked
