### ISSUE TITLE
BANS - my page empty

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#24]
Pic if the My page (domains #21 or favorite #22 ) is empty 
**no** "See all BANS’ transactions" available

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=40%3A1070
<img width="824" alt="Снимок экрана 2022-06-13 в 23 02 31" src="https://user-images.githubusercontent.com/94360080/173435430-54cdc21c-f3aa-4f43-8f46-556fd2a22a80.png">

**Comment by Denis-Asipenko** [comment]
1.There is no icon with text.
2."See all BANS’ transactions" is  available.

Current:

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/45556620/177945564-d6d58530-7f4e-4179-bf10-217db1e72e00.png">
Design:

![image](https://user-images.githubusercontent.com/45556620/177945629-f50952e3-7697-4360-a383-768b7acea5b8.png)

**Comment by AndreyDyakonov** [comment]
waiting this changes https://github.com/BeamMW/bans/issues/18#issuecomment-1183206594

**Comment by AndreyDyakonov** [comment]
Checked
