### ISSUE TITLE
BANS - BANS transactions page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#25]
BANS transactions page is open after click at See all BANS’ transactions
<img width="456" alt="Снимок экрана 2022-06-14 в 09 25 31" src="https://user-images.githubusercontent.com/94360080/173507881-45274ebe-f9f8-436e-9b31-2c8cd8a42f52.png">

The empty page with no receive transactions
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=51%3A1250
<img width="729" alt="Снимок экрана 2022-06-14 в 09 27 04" src="https://user-images.githubusercontent.com/94360080/173508119-25a762e7-9544-4441-a775-4914f1aa7ec7.png">

- Current balance - summarise balance for all domains. withdraw all - withdraw all funds from all domains 
- The list of user domains (domain name, expiration date, balance, withdraw  button), if the expiration date is less than 30 days - renew domain buttons appear #23 .
- Bans transactions history

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=32%3A76
<img width="580" alt="Снимок экрана 2022-06-14 в 09 30 48" src="https://user-images.githubusercontent.com/94360080/173508699-7e535203-f05a-46fb-8201-2db377c99e33.png">

Withdraw button, standart popup
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=36%3A1618
<img width="418" alt="Снимок экрана 2022-06-14 в 09 51 46" src="https://user-images.githubusercontent.com/94360080/173512115-6076b02f-a900-4697-8ce6-0a913c0a05f1.png">

Withdraw ALL button
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=36%3A2586
<img width="427" alt="Снимок экрана 2022-06-14 в 09 52 55" src="https://user-images.githubusercontent.com/94360080/173512339-91f4231f-bec3-491e-a388-63cd62e2c703.png">

Notification for withdraw all
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=36%3A2040
<img width="545" alt="Снимок экрана 2022-06-14 в 09 53 53" src="https://user-images.githubusercontent.com/94360080/173512489-a96eaf62-b5ee-4653-81f2-bd0f1e6e1130.png">

**Comment by VikMaevskaya** [comment]
BANS transaction list delay until  BANS V2

<img width="527" alt="Снимок экрана 2022-07-13 в 14 05 02" src="https://user-images.githubusercontent.com/94360080/178719408-949cd25d-96c6-4338-aba5-7f6f91e22fb7.png">

**Comment by Denis-Asipenko** [comment]
If the user clicked the withdrawal all button, then the withdrawal buttons for each domain separately should be disabled because the user will be able to initiate a large number of transactions that will be expired. If the user clicked the withdrawal button of a separate domain, then the withdrawal all button should be disabled because when it is clicked, this transaction will either completed faster or expire.

https://user-images.githubusercontent.com/45556620/181473937-a9545d45-1334-42a5-9944-c724aefc2a5a.mp4

**Comment by Denis-Asipenko** [comment]
checked
