### ISSUE TITLE
BANS - sell  BANS

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#26]
<img width="740" alt="Снимок экрана 2022-06-14 в 09 56 19" src="https://user-images.githubusercontent.com/94360080/173512967-c44f2d73-88ea-48cb-9e15-b2a622e1c90b.png">

Sell BANS popup flow
Chose the domain
set the price
in put buyer's public key
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=33%3A525
<img width="762" alt="Снимок экрана 2022-06-14 в 10 53 12" src="https://user-images.githubusercontent.com/94360080/173523834-4124c312-464c-4623-9061-61d9b92c9bdc.png">

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=33%3A773
<img width="577" alt="Снимок экрана 2022-06-14 в 11 07 36" src="https://user-images.githubusercontent.com/94360080/173526903-87546765-91c2-49ec-bf18-c92c76224fbc.png">

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=33%3A1014
<img width="566" alt="Снимок экрана 2022-06-14 в 11 08 03" src="https://user-images.githubusercontent.com/94360080/173527002-ca4b57ab-ded6-4b72-85ac-5105033291e0.png">

Confirm transaction
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=45%3A1371
<img width="321" alt="Снимок экрана 2022-06-14 в 11 08 46" src="https://user-images.githubusercontent.com/94360080/173527146-c83202ae-b375-4ffb-85bd-b4be82605bfa.png">

Notification
<img width="301" alt="Снимок экрана 2022-06-14 в 11 09 27" src="https://user-images.githubusercontent.com/94360080/173527265-f6753de5-6d0e-44a7-9a73-6efe6e18059c.png">

**Comment by AndreyDyakonov** [comment]
waiting this changes https://github.com/BeamMW/bans/issues/30#issuecomment-1186977815

**Comment by AndreyDyakonov** [comment]
1. Change "Bans" to "BANS"
2. Make this sentence from a new line (as in design)
3. Add ".beam" in the end of domain name (as in design)
4. Add "BEAM" on the right from Beam icon
5. Add "Buyer's Public Key" field
6.  - Change "Sell" to "sell"
     - Make the "sell" button size the same as "close"
     - Lift up the arrow up (the cross and the arrow should be on the same level)

![2022-07-22_10-07-13](https://user-images.githubusercontent.com/85252690/180394594-b13f63d7-1e1e-4ee2-8c39-27776b204426.png)

7. Make  the color and size the same as in the design

![2022-07-22_11-09-23](https://user-images.githubusercontent.com/85252690/180414636-3b638e48-5dfa-4e88-bd1f-7324451d3051.png)

8. Only numbers and "dot" can be entered in the funds field (there cannot be more than one zero before the dot)

![2022-07-22_11-11-05](https://user-images.githubusercontent.com/85252690/180415031-fdc6c23c-27dd-4c1b-ad31-6e341a23a8d7.png)

**Comment by AndreyDyakonov** [comment]
1. Change "Sell" to "sell" 

![2022-07-26_13-01-39](https://user-images.githubusercontent.com/85252690/180980159-c3f31a8b-0a0f-4f53-ab5d-1dea14d79242.png)

2. Reduce the distance between the "up arrow" and "sell" (it should be the same as between the "cross" and "close")

![2022-07-26_13-00-16](https://user-images.githubusercontent.com/85252690/180980563-18d7c705-d791-4845-92f2-317db625c5a9.png)

3. Make the "up arrow" in height smaller (it should be the same height as the "cross")

![2022-07-26_12-59-15](https://user-images.githubusercontent.com/85252690/180980903-c33eb2d4-b065-4ec3-8a64-3063dc27303c.png)

4. If we click on any area outside the dropdown list it should be closed

https://user-images.githubusercontent.com/85252690/180981385-d13a6bb1-c1aa-47d0-8f0a-638f0bcdafea.mp4

**Comment by AndreyDyakonov** [comment]
1. Please make an alignment (for a domain that is not on sale) all items should start with the same indentation 
(for example with "sell")


![2022-07-28_10-44-06](https://user-images.githubusercontent.com/85252690/181450807-69b024e7-cc65-45f1-9d1d-5e97b75a26a8.png)

2. Distance between the "arrow" and "sell" should be the same as between the "cross" and "close"
3. The "sell" button should be the same size as the "close" button

![2022-07-28_10-50-13](https://user-images.githubusercontent.com/85252690/181452095-cf2c7f1c-cbf9-4874-bd44-850a425330ce.png)

4. Change the color of the entered amount and the cursor in this field according to the design

![2022-07-28_10-55-12](https://user-images.githubusercontent.com/85252690/181452545-1fa5451a-14a2-47f1-a913-49ffc4c3dfe2.png)

5. Please make that clicking again to "arrow" closes the drop-down list

https://user-images.githubusercontent.com/85252690/181453175-9ac06b8b-9c46-4bca-801e-a1bb1bd8787f.mp4

**Comment by AndreyDyakonov** [comment]
Please make it so that when a single click on the "domain name field" or the "drop-down list arrow" closes the drop-down list
(now, with a single click on this field or arrow, the list is reopened)

![2022-07-29_07-25-44](https://user-images.githubusercontent.com/85252690/181683019-92b34a14-a879-4b43-abe7-2073d40587fa.png)


https://user-images.githubusercontent.com/85252690/181683047-2b318bc5-e74c-4a48-83d5-2b20ed5d230f.mp4

**Comment by AndreyDyakonov** [comment]
Checked
