### ISSUE TITLE
BANS - create notification "domain on sale"

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#27]
when the user has any unavailable domain in favorites  and this domaine become "on sale" show notification on the main page.

non pop up notification. info block with possibility to close it.

text: the one of your favorite domains is on sale now.
           more details: personal page -> favorite

**Comment by dariatarakanova** [comment]
please have a look https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=568%3A934

**Comment by AndreyDyakonov** [comment]
1. "More Details" button should be aligned on the right side (near the "cross" button)
(regardless of the text in the notification, the "More Details" and "cross" buttons should be aligned on the right side and be strictly one under one in the notification chain)

2. Button "More Details" must be strictly in one line (without hyphenation as the text in notification)

![2022-07-21_12-10-25](https://user-images.githubusercontent.com/85252690/180180319-dc5e0998-579d-4eaf-848e-1fe3f4863965.png)

**Comment by AndreyDyakonov** [comment]
Alignment in notifications is not done
1. If the notification text is long, it can be moved to the next line
2. "More Details" button is aligned on the right side to the left of the "cross" button and in one line
here is an example of what I meant:

![2022-07-21_19-04-49](https://user-images.githubusercontent.com/85252690/180263262-a7151d26-a028-4c4b-91e8-e0434eb6524b.png)

**Comment by AndreyDyakonov** [comment]
1. Notifications only work when funds have been received to your domain name, if the favorite domain is for sale or someone has bought your domain, then notifications do not come

2. If the notification uses a domain name with the maximum number of characters (30) - alignment don't work 

![photo_2022-07-29_10-08-24](https://user-images.githubusercontent.com/85252690/181703105-4cb014e3-6a01-414a-9b62-4a184043d5dc.jpg)

**Comment by AndreyDyakonov** [comment]
Checked
