### ISSUE TITLE
Bans - to add options to the menu

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#28]
add new options: 
1.gift domain (like at the nft marketplace) + flow
2. Put up domain for sale/ remove from sale +flow
3. if domain on sale - change the price (pup up like for put on sale)

flow for "Put up domain for sale": pop up to set up a price. chose domain, set a price in beam. cancel/approve buttons
flow for "remove from sale" - pop up - Are you sure you want to take it off the sale?  cancel/approve buttons

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=104%3A718
<img width="138" alt="Снимок экрана 2022-06-27 в 17 31 19" src="https://user-images.githubusercontent.com/94360080/175965756-57ad8f1e-ab8a-4c1e-a732-2496de3df44c.png">

**Comment by dariatarakanova** [comment]
1) gift flow
1.1) option https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=104%3A718
1.2) popup with address field https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=569%3A1134
1.3) filled address field https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=569%3A1369

**Comment by Denis-Asipenko** [comment]
1. there is no way to renew your subscription for domain that are on sale

<img width="1096" alt="2022-07-26_15-16-28" src="https://user-images.githubusercontent.com/45556620/181009227-3e269d12-8909-4143-af2a-29ebc4a4865b.png">


2.correct to small letters according to the design

current:
<img width="1020" alt="2022-07-26_15-17-35" src="https://user-images.githubusercontent.com/45556620/181007384-7d4ad31d-4864-4dfa-b76a-cc5be372a8f2.png">
<img width="1023" alt="2022-07-26_15-16-28" src="https://user-images.githubusercontent.com/45556620/181007395-e82a9070-6725-456e-a738-37003223d720.png">


design:
<img width="829" alt="2022-07-26_15-38-34" src="https://user-images.githubusercontent.com/45556620/181007943-f0145d8f-8f8f-41fa-90e5-0aa945e68e95.png">
<img width="1132" alt="2022-07-26_15-39-37" src="https://user-images.githubusercontent.com/45556620/181007838-1b675404-8f5c-4069-906f-53e773209acd.png">

**Comment by Denis-Asipenko** [comment]
checked
