### ISSUE TITLE
BANS - empty page 

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#29]
need to create an empty page by analogy.
the text: the BANS will appear on the page as soon as the transaction is completed.

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=40%3A1070

**Comment by dariatarakanova** [comment]
screen here https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=568%3A638

**Comment by AndreyDyakonov** [comment]
it is not done
it is necessary that after confirming the buy of the first domain name, the text on the  page "All" should be **"the BANS will appear on the page as soon as the transaction is completed"**

![2022-07-18_10-24-59](https://user-images.githubusercontent.com/85252690/179463245-513fbedf-aa16-4276-a53e-2d88f5cd7e6d.png)

**Comment by AndreyDyakonov** [comment]
Checked
