### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#3]
IF Bans name available, the click on it open Registration form below.
the price count automaticaly. Must to be - usd equivalent.
Buttons 'complete registration' goes to standart beam' payment window.

<img width="1006" alt="Снимок экрана 2022-06-01 в 17 34 32" src="https://user-images.githubusercontent.com/94360080/171432785-13679a0d-4839-42ee-a5aa-d248fccac046.png">

**Comment by dariatarakanova** [comment]
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=10%3A362

<img width="807" alt="image" src="https://user-images.githubusercontent.com/47353570/171702546-445c6f2d-e939-4f62-b205-1a4ad0b10602.png">
