### ISSUE TITLE
Bans - resale doman. notification + flow

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#31]
The view and flow will use on the main page and on the Favorit page.

**Comment by dariatarakanova** [comment]
Domain list
1) Add icon "sell" to option https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=104%3A718
2) Fill domain and amount on popup https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=33%3A525
3) Confirmation https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=45%3A1371

Favorite domain screen:
4) Mark domain on sale with text and border, add price https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=571%3A1604

Search screen:
5) If user search reseled domain shows domain name with expiration date, price, button buy and border https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=655%3A766
6) After "buy" shows popup https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=664%3A2119
7) And confirmation https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=664%3A2411

**Comment by AndreyDyakonov** [comment]
1. Change "sell BANS" to "sell"
2. Change "Transfer" to "transfer" 

![2022-07-25_15-16-17](https://user-images.githubusercontent.com/85252690/180775874-060a4c9d-9628-4a35-875d-904aa2455881.png)

3. Make the font the same as in the design

![2022-07-25_15-15-30](https://user-images.githubusercontent.com/85252690/180776029-2207f1ec-55f2-462f-90bf-e938d11dc300.png)

**Comment by AndreyDyakonov** [comment]
Remove "1" in the end of word "Attention"

![2022-07-28_13-59-19](https://user-images.githubusercontent.com/85252690/181490142-be56d599-5c91-48ca-9c71-03f532a8bc43.png)

**Comment by AndreyDyakonov** [comment]
Checked
