### ISSUE TITLE
BANS - transfer change text

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#32]
please change the text to "Paste the Publisher key of the recipient of this domain."

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=569%3A1134

<img width="883" alt="Снимок экрана 2022-07-04 в 19 15 07" src="https://user-images.githubusercontent.com/94360080/177190911-a29521f6-95ce-4553-bfb4-9b7bede15baf.png">

**Comment by dariatarakanova** [comment]
done @VikMaevskaya

**Comment by AndreyDyakonov** [comment]
1. Please make the font the same as in the design
2. Please remove the white border around the input field
3. Please make the word "transfer" with a lowercase letter

![2022-07-15_17-02-57](https://user-images.githubusercontent.com/85252690/179239907-04ce25c6-90d9-4095-a788-64af9d58de46.png)
