### ISSUE TITLE
Registration price isn't display

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/bans#33]
Registration price isn't display when buying and when renew subscriptio

https://user-images.githubusercontent.com/45556620/177778832-e38ffbb9-6ffc-41e7-9a5c-5a372fd56715.mp4

n

**Comment by AndreyDyakonov** [comment]
1. Registration price must changing when we use 3 or 4 or 5+ characters and with an increase in the number of years,
**now "Registration price" display incorrectly** and not changing

<img width="467" alt="1111" src="https://user-images.githubusercontent.com/85252690/178280953-33edc01c-96fb-4e3c-bbc6-e7bbadbe1d6f.png">

![3333](https://user-images.githubusercontent.com/85252690/178284928-d4e9b790-db3d-441a-9c55-6a4246da4293.png)

https://user-images.githubusercontent.com/85252690/178281385-319ee951-cfee-4085-9ce3-62febe20a00f.mp4

2. When we click "plus" button for 5 years or more(5 click or more), the button is displayed as inactive

![2222](https://user-images.githubusercontent.com/85252690/178285141-c255b4ef-7fc1-47d9-962a-120ed33868f7.png)


https://user-images.githubusercontent.com/85252690/178285536-73d7cd40-cc2b-4e92-be82-625648a34c7b.mp4


3. If we use domain name with 4 characters price must be **160 Beam** (now is 16 Beam)

<img width="450" src="https://user-images.githubusercontent.com/85252690/178279480-2b32358e-37d2-4127-8db5-71264e221212.png">

<img width="450" src="https://user-images.githubusercontent.com/85252690/178279119-ecc0ded9-4f82-4f1a-b0ef-4b57e5e54f93.png">

https://user-images.githubusercontent.com/85252690/178279585-dfd177a1-a008-4f18-b747-0d8b78fd2e00.mp4

**Comment by AndreyDyakonov** [comment]
1. Price should change according to the spec :
5+ character.BEAM names: $10 in BEAM per year.
4 character.BEAM names: $120 in BEAM per year.
3 character.BEAM names $320 in BEAM per year.

now for all price categories is equal to 16 Beam and increases by 16 Beam every year - it is not correctly 

https://user-images.githubusercontent.com/85252690/178957896-740acf1c-ba46-4344-8a06-c3cc33045577.mp4

2. When we click "plus" button for 5 years or more(5 click or more), the button is displayed as inactive (it is not done)

![image](https://user-images.githubusercontent.com/85252690/178958060-c7d79e2e-20bc-4b59-ac61-b5f17bcc0b82.png)

https://user-images.githubusercontent.com/85252690/178285536-73d7cd40-cc2b-4e92-be82-625648a34c7b.mp4

**Comment by AndreyDyakonov** [comment]
Checked
