### ISSUE TITLE
The scroll bar is displayed in windowed mode

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/bans#34]
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/45556620/177779839-d00e45c0-18a7-4088-8941-f6765742302d.png">

**Comment by AndreyDyakonov** [comment]
If scrollbar needed on the page, please make it as in the others DApp's (for example as in Gallery 2.0)

![2022-07-11_14-39-14](https://user-images.githubusercontent.com/85252690/178257699-e589b5f3-2b4c-4714-b72f-873efe1d46fa.png)

https://user-images.githubusercontent.com/85252690/178257784-b12ac485-57c5-4e26-a92b-181fde2630ea.mp4

**Comment by AndreyDyakonov** [comment]
Checked
