### ISSUE TITLE
Texts, fonts and others to fix

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#39]
the main page
need to be
<img width="620" alt="Снимок экрана 2022-07-08 в 12 36 06" src="https://user-images.githubusercontent.com/94360080/177963724-bfad8044-e203-4ca2-82c2-e8314e46759b.png">

how it is
<img width="672" alt="Снимок экрана 2022-07-08 в 12 36 36" src="https://user-images.githubusercontent.com/94360080/177963804-10e8238f-f0cb-47c2-9df0-2510962a2417.png">

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=2%3A495

**Comment by VikMaevskaya** [comment]
send funds 

need to be
<img width="670" alt="Снимок экрана 2022-07-08 в 12 58 18" src="https://user-images.githubusercontent.com/94360080/177967888-18518519-1695-49ec-98c2-73639542f337.png">

how it is
<img width="576" alt="Снимок экрана 2022-07-08 в 12 58 31" src="https://user-images.githubusercontent.com/94360080/177967865-112fae56-2e55-41a5-b2e7-1f89e88d16af.png">

**Comment by Denis-Asipenko** [comment]
checked
