### ISSUE TITLE
Updated on FAVORITES tab

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/bans#43]
1) Remove icon "heart"
2) Add "remove from favourite" to options
3) Replace icon "copy" closer to domain name
5) Add button "send funds"
4) Replace "available" under domain name 
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/47353570/178288479-094532e9-a0e3-463e-91dd-872fae6be674.png">

https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=911%3A1296

Also place icon "copy" closer to domain name on ALL tab
<img width="445" alt="image" src="https://user-images.githubusercontent.com/47353570/178289594-a50c0101-8265-490f-b8d1-8b699e40d31a.png">

**Comment by AndreyDyakonov** [comment]
Checked
