### ISSUE TITLE
notification your favorite domain is available when I don't have any favorites

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#47]
<img width="810" alt="Снимок экрана 2022-07-14 в 12 06 47" src="https://user-images.githubusercontent.com/94360080/178959553-d28529c1-8420-425f-8dc1-11389dfb92ff.png">
<img width="815" alt="Снимок экрана 2022-07-14 в 13 11 59" src="https://user-images.githubusercontent.com/94360080/178959568-5dc7f5e7-8b4c-4142-b518-3c6dfa3e52cc.png">

**Comment by AndreyDyakonov** [comment]
waiting this task https://github.com/BeamMW/bans/issues/27

**Comment by AndreyDyakonov** [comment]
Checked
