### ISSUE TITLE
Change the app name in the  My DApp store

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/bans#52]
Change the app name in the  My DApp store according design
![image](https://user-images.githubusercontent.com/45556620/180433239-637cec28-34cb-46a6-a0b7-eb724eb763b2.png)
![image](https://user-images.githubusercontent.com/45556620/180433113-b79cac84-0f88-43dd-a983-ffdece38a69a.png)

**Comment by viktarmikhan** [comment]
new name is too long
