### ISSUE TITLE
BANS - info for FAQ

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#55]
Please, fill in the FAQ. question number not needed
the link for the first question will be later.

https://docs.google.com/document/d/1c65aifdfLOBRSJNDhX40Xw5SZYy58bCHOWrX-wVhrPM/edit#heading=h.8pae3q13w0or

**Comment by AndreyDyakonov** [comment]
Now in FAQ added only 5 first questions, please add all  other questions (as in google docs)

**Comment by AndreyDyakonov** [comment]
waiting "Follow this guide" link by @VikMaevskaya

**Comment by AndreyDyakonov** [comment]
Checked
