### ISSUE TITLE
Main page "Back" button

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#56]
In design, we didn't have a **Back** button. Please, place it at the same level as the menu.
<img width="946" alt="Снимок экрана 2022-07-28 в 12 42 48" src="https://user-images.githubusercontent.com/94360080/181475529-fd9d8c79-75e5-4292-b1de-8beb1d621a11.png">

**Comment by AndreyDyakonov** [comment]
Please give back the logo and the DApp name

![2022-07-28_15-40-33](https://user-images.githubusercontent.com/85252690/181507517-4226afed-a07c-4ccc-b726-3056529f0351.png)

**Comment by AndreyDyakonov** [comment]
Checked
