### ISSUE TITLE
Set max width to container to not allow it to grow.

### ISSUE THREAD

**Issue by mkrtchyan98** [BeamMW/bans#58]

**Comment by AndreyDyakonov** [comment]
If we don't have any own or favorites domains  then in full size wallet "my page" - "all domain" and "favorite" display incorrectly

![2022-07-29_10-39-10](https://user-images.githubusercontent.com/85252690/181709795-cd6f5c9a-6dff-4f21-ac87-7ddff8b7228c.png)

https://user-images.githubusercontent.com/85252690/181709941-33815073-e486-4a57-8473-b9270aa1e0ef.mp4

**Comment by AndreyDyakonov** [comment]
Checked
