### ISSUE TITLE
BANS user's personal page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#6]
<img width="821" alt="Снимок экрана 2022-06-06 в 16 28 01" src="https://user-images.githubusercontent.com/94360080/172170123-375171b5-35f6-4060-ac1a-43ef01c7ecd8.png">

**Comment by dariatarakanova** [comment]
1) All BANS https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=7%3A1007

2) Favorite BANS https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=31%3A657

3) Renew https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=36%3A410

4) If user click "available" in favorite tab https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=36%3A683
