### ISSUE TITLE
Registering a new domain leads to crash DApp

### ISSUE THREAD

**Issue by AndreyDyakonov** [BeamMW/bans#63]
When we registering a new domain name and stay at the registration window - BANS DApp is crashing 
in normal working should be transition to the "my page" - "all domain"

(note: if we registering a new domain name and then click back and return in main page - DApp working normally)

https://user-images.githubusercontent.com/85252690/181685760-33ffdcc0-1c17-4c99-bb1a-67791b998e35.mp4

**Comment by Denis-Asipenko** [comment]
checked
