### ISSUE TITLE
Add multi assets choice to the BANS

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#66]
First 3: BEAM, BEAMX, NPH
the others like for Atomic swap, cant find design in zepplin

send funds to the bans
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=660%3A1414

sell bans
https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=33%3A525

<img width="248" alt="Снимок экрана 2022-08-29 в 14 55 29" src="https://user-images.githubusercontent.com/94360080/187202594-85bab946-310d-4e74-8c67-cce16a4811eb.png">

**Comment by dariatarakanova** [comment]
1) Send funds to the BANS https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=1618%3A1169
2) Sell BANS https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=1647%3A1373
