### ISSUE TITLE
Bans Transaction Info page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/bans#7]
<img width="783" alt="Снимок экрана 2022-06-06 в 16 28 12" src="https://user-images.githubusercontent.com/94360080/172233805-d1b93249-2236-40b8-a314-6e6225c91d8e.png">

**Comment by dariatarakanova** [comment]
1) Transactions screen https://www.figma.com/file/gqD4UzxM1AUxrYAtJ7ullC/BANS?node-id=32%3A76
